services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: sital
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: expense_tracker
    ports:
      - "5555:5432"
    volumes:
      - ./server/db_data:/var/lib/postgresql/

  backend:
    build: ./server
    ports:
      - "5001:5000"
    env_file:
      - ./server/.env
    depends_on: 
      - db
  
  frontend:
    build: ./client
    ports:
      - "3001:3000"
    env_file:
      - ./client/.env
    depends_on:
      - backend
  
