services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: sital
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: expense_tracker
    ports:
      - "5555:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/
  
  
